server:
  port: 8082
postgre:
  host: localhost
  port: 5432
  username: root
  password: Chubaduy@123
  dbName: crm_dev
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifeTime: 3600
logger:
  logLevel: debug
  fileLogName: "./storages/logs/dev.001.log"
  fileName:   "./storages/logs/dev.xxx.log"
  maxSize:    500
  maxBackups: 3
  maxAge:     28
  compress:   true